language: cpp

git:
  depth: 3

env:
  global:
#    - OTB_URL=https://www.orfeo-toolbox.org/packages/archives/OTB
    - OTB_URL=https://www.orfeo-toolbox.org/packages/ci/latest
    - OTB_VER=6.7.0

matrix:
  include:
  #~ - os: linux
    #~ dist: bionic
    #~ compiler: gcc
    #~ sudo: required
    #~ before_install:
      #~ - sudo apt-get install -y
          #~ ninja-build
          #~ libglvnd-dev
          #~ libglu1-mesa-dev
          #~ python3-numpy
    #~ env:
      #~ - OTB_OS=Linux64
  #~ - os: osx
    #~ osx_image: xcode10.2
    #~ compiler: clang
    #~ before_install:
      #~ - brew install ninja libomp
    #~ env:
      #~ - OTB_OS=Darwin64
  - os: windows
    before_install:
      - choco install python
      - choco install ninja
    env:
      - OTB_OS=Win64
    install:
      - wget ${OTB_URL}/OTB-${OTB_VER}-${OTB_OS}.zip
      - 7z x -y OTB-${OTB_VER}-${OTB_OS}.zip
      - mv OTB-${OTB_VER}-${OTB_OS} xdk

install:
  - wget ${OTB_URL}/OTB-${OTB_VER}-${OTB_OS}.run
  - chmod +x OTB-${OTB_VER}-${OTB_OS}.run
  - ./OTB-${OTB_VER}-${OTB_OS}.run --target xdk

script:
  - source setup_windows_env.sh
  - echo $PATH
  - ctest -VV -S ./ci.cmake
