language: cpp

git:
  depth: 3

env:
  global:
#    - OTB_URL=https://www.orfeo-toolbox.org/packages/archives/OTB
    - OTB_URL=https://www.orfeo-toolbox.org/packages/ci/latest
    - OTB_VER=6.7.0

matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    sudo: required
    before_install:
      - sudo apt-get install -y
          ninja-build
          libglvnd-dev
          libglu1-mesa-dev
          python3-dev
          python3-numpy
    env:
      - OTB_OS=Linux64
  - os: osx
    compiler: clang
    before_install:
      - brew install ninja libomp
    env:
      - OTB_OS=Darwin64

install:
  - wget ${OTB_URL}/OTB-${OTB_VER}-${OTB_OS}.run
  - chmod +x OTB-${OTB_VER}-${OTB_OS}.run
  - ./OTB-${OTB_VER}-${OTB_OS}.run --target xdk

script:
  - ctest -VV -S ./ci.cmake
