os: linux
language: cpp
compiler: gcc
sudo: required
dist: bionic

before_install:
  - sudo apt-get install -y wget file ninja

install:
  - wget https://www.orfeo-toolbox.org/packages/OTB-6.6.1-Linux64.run
  - chmod +x OTB-6.6.1-Linux64.run
  - ./OTB-6.6.1-Linux64.run --target xdk

script:
  - ctest -VV -S ./ci.cmake
